services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agriculture
    volumes:
      - agriculture-postgres-data:/var/lib/postgresql/data
    networks:
      - agriculture-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - agriculture-network

networks:
  agriculture-network:

volumes:
  agriculture-postgres-data: